language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.0
    - android-22

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repositoriy
notifications:
  irc: "irc.epd-me.net#yaaic"
